export const LOAD_ALL_CHEF_CLASSES_SUCCESS = "LOAD_ALL_CHEF_CLASSES_SUCCESS";
export const LOAD_CLASS_SUCCESS = "LOAD_CLASS_SUCCESS";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const SELECT_CLASS = "SELECT_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
export const ADD_TIME_SLOT = "ADD_TIME_SLOT"
export const DELETE_TIME_SLOT = "DELETE_TIME_SLOT";