export const UPDATE_BOOKING_DETAILS = "UPDATE_BOOKING_DETAILS";
export const LOAD_ClASS_DATA_SUCCESS = "LOAD_ClASS_DATA_SUCCESS";
export const SUBMIT_BOOKING_SUCCESS = "SUBMIT_BOOKING_SUCCESS";
export const SUBMIT_BOOKING_FAILED = "SUBMIT_BOOKING_FAILED";
export const SELECT_CLASS_FOR_BOOKING = "SELECT_CLASS_FOR_BOOKING";