export const LOAD_POSTS = "LOAD_POSTS";
export const SELECT_BLOG_POST = "SElECT_BLOG_POST";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";
export const LOAD_ALL_POSTS_SUCCESS = "LOAD_ALL_POSTS_SUCCESS";